apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-endpoint
  template:
    metadata:
      labels:
        app: llm-endpoint
    spec:
      containers:
      - name: llm
        image: vllm/vllm-openai:latest
        args: ["--model", "mistralai/Mistral-7B-Instruct-v0.1"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-endpoint
spec:
  type: LoadBalancer
  selector:
    app: llm-endpoint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

